[Icon Theme]
Name=LowContrast
Comment=Low Contrast Theme
Directories=48x48/actions,48x48/apps,48x48/categories,48x48/devices,48x48/stock
Inherits=gnome

[48x48/apps]
Size=48
Context=Applications
Type=Scalable

[48x48/actions]
Size=48
Context=Actions
Type=Scalable

[48x48/categories]
Size=48
Context=Categories
Type=Scalable

[48x48/devices]
Size=48
Context=Devices
Type=Scalable

[48x48/stock]
Size=48
Context=Stock
Type=Scalable
