#! /bin/sh
# Copyright (c) 1995-2000 SuSE GmbH Nuernberg, Germany.
#
# Author: Werner Fink <werner@suse.de>, 1996-2001
#
# /etc/init.d/cron
#
#   and symbolic its link
#
# /usr/sbin/rccron
#
# System startup script for the cron daemon
#
### BEGIN INIT INFO
# Provides:       cron
# Required-Start: $remote_fs $syslog $time
# Should-Start:   $network smtp
# Required-Stop:  $remote_fs $syslog
# Should-Stop:	  $network smtp
# Default-Start:  2 3 5
# Default-Stop:   0 1 6
# Short-Description: Cron job service
# Description:    Cron job service
### END INIT INFO

CRON_BIN=/usr/sbin/cron
test -x $CRON_BIN || exit 5
PIDFILE=/var/run/cron.pid

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_failed <num>  set local and overall rc status to <num><num>
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status
. /etc/rc.status

# First reset status of this service
rc_reset

# Return values acc. to LSB for all commands but status:
# 0 - success
# 1 - generic or unspecified error
# 2 - invalid or excess argument(s)
# 3 - unimplemented feature (e.g. "reload")
# 4 - insufficient privilege
# 5 - program is not installed
# 6 - program is not configured
# 7 - program is not running
# 
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signalling is not supported) are
# considered a success.

allow_deny_move_info() {
    echo "WARNING: /var/spool/cron/allow and /var/spool/cron/deny have moved"
    echo "to /etc/cron.allow and /etc/cron.deny."
    echo "Please merge or move these files to get cron access rules restored."
}

case "$1" in
    start)
        for al_de in {allow,deny}{,.rpmsave,.rpmorig} ; do
		if [ -f /var/spool/cron/$al_de ] ; then
			allow_deny_move_info
			break
		fi
	done
	echo -n "Starting CRON daemon"
	## Start daemon with startproc(8). If this fails
	## the echo return value is set appropriate.

	# NOTE: startproc return 0, even if service is 
	# already running to match LSB spec.
	startproc -p $PIDFILE $CRON_BIN
	#startproc -f $CRON_BIN

	# Remember status and be verbose
	rc_status -v
	;;
    stop)
	echo -n "Shutting down CRON daemon"
	## Stop daemon with killproc(8) and if this fails
	## set echo the echo return value.

	killproc -TERM -p $PIDFILE $CRON_BIN 

	# Remember status and be verbose
	rc_status -v
	;;
    try-restart)
	## Stop the service and if this succeeds (i.e. the 
	## service was running before), start it again.
	## Note: try-restart is not (yet) part of LSB (as of 0.7.5)
	$0 status >/dev/null &&  $0 restart

	# Remember status and be quiet
	rc_status
	;;
    restart)
	## Stop the service and regardless of whether it was
	## running or not, start it again.
	$0 stop
	$0 start

	# Remember status and be quiet
	rc_status
	;;
    force-reload)
	## Signal the daemon to reload its config. Most daemons
	## do this on signal 1 (SIGHUP).
	## If it does not support it, restart.

	echo -n "Reload service Cron"
	## if it supports it:
        ## cron monitors /etc/crontab  anyway
	
	checkproc $CRON_BIN
	rc_status -v

	## Otherwise:
	#$0 stop  &&  $0 start
	#rc_status
	;;
    reload)
	## Like force-reload, but if daemon does not support
	## signalling, do nothing (!)

	## Otherwise if it does not support reload:
	rc_status -v
	;;
    status)
	echo -n "Checking for Cron: "
	## Check status with checkproc(8), if process is running
	## checkproc will return with exit status 0.

	# Status has a slightly different for the status command:
	# 0 - service running
	# 1 - service dead, but /var/run/  pid  file exists
	# 2 - service dead, but /var/lock/ lock file exists
	# 3 - service not running

	# NOTE: checkproc returns LSB compliant status values.
	checkproc $CRON_BIN
	rc_status -v
	;;
    probe)
	## Optional: Probe for the necessity of a reload,
	## give out the argument which is required for a reload.

	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
	exit 1
	;;
esac
rc_exit
