#!/bin/sh
#
#
# clean_catman. This script was split off cron.daily
# Please add your local changes to cron.daily.local
# since this file will be overwritten, when updating your system.
#
# Copyright (c) 1996-2002 SuSE GmbH Nuernberg, Germany.   
#
# please send bugfixes or comments to feedback@suse.de.
#
# Author: Burchard Steinbild <feedback@suse.de>, 1996
#         Florian La Roche   <feedback@suse.de>, 1996
#


#
# paranoia settings
#
umask 022

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

if [ -f /etc/sysconfig/cron ] ; then
    . /etc/sysconfig/cron
fi

#
# Delete too old preformatted man-pages.
#
if test "$DELETE_OLD_CATMAN" = yes ; then
    if test -z "$CATMAN_ATIME" ; then
	# Default is 7 days
	CATMAN_ATIME=7
    fi
    test -e /var/cache/man -a -x /usr/bin/safe-rm && \
	find /var/cache/man -name '*.gz' -type f -atime +$CATMAN_ATIME  -print0 | \
	xargs --no-run-if-empty --max-lines=200 --null -- /usr/bin/safe-rm
fi

exit 0
